//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.CacheServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CacheServiceReference.ICacheService")]
    public interface ICacheService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICacheService/getFiles", ReplyAction="http://tempuri.org/ICacheService/getFilesResponse")]
        string[] getFiles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICacheService/getFiles", ReplyAction="http://tempuri.org/ICacheService/getFilesResponse")]
        System.Threading.Tasks.Task<string[]> getFilesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICacheService/getFile", ReplyAction="http://tempuri.org/ICacheService/getFileResponse")]
        System.IO.Stream getFile(string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICacheService/getFile", ReplyAction="http://tempuri.org/ICacheService/getFileResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> getFileAsync(string fileName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICacheServiceChannel : Client.CacheServiceReference.ICacheService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CacheServiceClient : System.ServiceModel.ClientBase<Client.CacheServiceReference.ICacheService>, Client.CacheServiceReference.ICacheService {
        
        public CacheServiceClient() {
        }
        
        public CacheServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CacheServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CacheServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CacheServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] getFiles() {
            return base.Channel.getFiles();
        }
        
        public System.Threading.Tasks.Task<string[]> getFilesAsync() {
            return base.Channel.getFilesAsync();
        }
        
        public System.IO.Stream getFile(string fileName) {
            return base.Channel.getFile(fileName);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> getFileAsync(string fileName) {
            return base.Channel.getFileAsync(fileName);
        }
    }
}
